"""mj

Revision ID: 46386b760ac9
Revises: deb5806c22df
Create Date: 2025-04-23 19:40:01.088678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46386b760ac9'
down_revision = 'deb5806c22df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mj_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_imagine_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_cn', sa.Text(), nullable=True),
    sa.Column('opt_uuid', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROCESSING', 'SUCCESS', 'FAIL', 'CANCEL', name='mjtaskstatus'), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('oss_image_url', sa.String(length=1024), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_overview', sa.Text(), nullable=True),
    sa.Column('error_show', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('api_source', sa.String(length=64), nullable=True),
    sa.Column('api_result', sa.String(length=64), nullable=True),
    sa.Column('api_request_json', sa.JSON(), nullable=True),
    sa.Column('api_response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('api_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['mj_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mj_tasks_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mj_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mj_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mj_tasks_user_imagine_id'), ['user_imagine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mj_tasks_user_imagine_id'))
        batch_op.drop_index(batch_op.f('ix_mj_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_mj_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_mj_tasks_message_id'))

    op.drop_table('mj_tasks')
    # ### end Alembic commands ###
