"""mj 去掉多余的字段

Revision ID: 510dcff24d54
Revises: 46386b760ac9
Create Date: 2025-04-23 21:23:50.641153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '510dcff24d54'
down_revision = '46386b760ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_mj_tasks_image_id'), ['image_id'], unique=False)
        batch_op.drop_column('progress')
        batch_op.drop_column('error_code')
        batch_op.drop_column('prompt_cn')
        batch_op.drop_column('api_source')
        batch_op.drop_column('error_message')
        batch_op.drop_column('api_result')
        batch_op.drop_column('api_response_json')
        batch_op.drop_column('api_request_json')
        batch_op.drop_column('image_url')
        batch_op.drop_column('error_overview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_overview', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True))
        batch_op.add_column(sa.Column('api_request_json', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('api_response_json', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('api_result', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
        batch_op.add_column(sa.Column('error_message', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('api_source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True))
        batch_op.add_column(sa.Column('prompt_cn', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('error_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True))
        batch_op.add_column(sa.Column('progress', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_mj_tasks_image_id'))
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
