"""message_id to int

Revision ID: 71cbd65a1aff
Revises: 824cf072fcae
Create Date: 2025-05-06 23:17:37.459157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71cbd65a1aff'
down_revision = '824cf072fcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               type_=sa.Integer(),
               nullable=True,
               comment=None,
               existing_comment='消息ID')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               nullable=False,
               comment='消息ID')

    # ### end Alembic commands ###
