"""add status

Revision ID: 747d0a4be9dc
Revises: 71cbd65a1aff
Create Date: 2025-05-10 12:06:36.108894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747d0a4be9dc'
down_revision = '71cbd65a1aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'chat_messages', ['message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
