"""Add MessageHtml model

Revision ID: 824cf072fcae
Revises: c6f9ff29718e
Create Date: 2025-05-06 22:35:35.187916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824cf072fcae'
down_revision = 'c6f9ff29718e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_html',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False, comment='消息ID'),
    sa.Column('html_code', sa.Text(), nullable=False, comment='HTML代码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_html_message_id'), ['message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('message_html', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_html_message_id'))

    op.drop_table('message_html')
    # ### end Alembic commands ###
