"""init

Revision ID: deb5806c22df
Revises: 
Create Date: 2025-04-22 22:16:12.403182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deb5806c22df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_mj_tasks_message_id')
        batch_op.drop_index('ix_mj_tasks_status')
        batch_op.drop_index('ix_mj_tasks_user_id')
        batch_op.drop_index('ix_mj_tasks_user_imagine_id')

    op.drop_table('mj_tasks')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dify_api_key_ds', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('dify_api_key_ds')

    op.create_table('mj_tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_imagine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prompt', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('prompt_cn', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('opt_uuid', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.Column('status', mysql.ENUM('WAITING', 'IN_PROCESSING', 'SUCCESS', 'FAIL', 'CANCEL'), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True),
    sa.Column('oss_image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True),
    sa.Column('actions_json', mysql.JSON(), nullable=True),
    sa.Column('progress', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('error_overview', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('error_show', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('parent_task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('api_source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('api_result', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('api_request_json', mysql.JSON(), nullable=True),
    sa.Column('api_response_json', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('api_call_at', mysql.DATETIME(), nullable=True),
    sa.Column('api_end_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name='mj_tasks_ibfk_2'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['mj_tasks.id'], name='mj_tasks_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mj_tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mj_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_mj_tasks_user_imagine_id', ['user_imagine_id'], unique=False)
        batch_op.create_index('ix_mj_tasks_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_mj_tasks_status', ['status'], unique=False)
        batch_op.create_index('ix_mj_tasks_message_id', ['message_id'], unique=False)

    # ### end Alembic commands ###
